[manifest]
version = "1.0"
dump_lua = true
priority = 10

[[patches]]
[patches.copy]
target = "game.lua"
position = "append"
sources = [
  "lib/Balatro-Settings/src/Settings.lua"
]

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local t = create_UIBox_generic_options({back_func = 'options',contents = {create_tabs("
position = "before"
match_indent = true
overwrite = false
payload = '''
if not DV.settings_tab then
  tabs[#tabs+1] = DV.create_settings_tab()
  DV.settings_tab = true
end
'''

[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = '''tab_alignment = 'tm',\n\s+snap_to_nav = true}\n\s+\)}}\)\n'''
position = "after"
match_indent = true
overwrite = false
# Reset for next UI create/update
payload = '''
DV.settings_tab = false
'''
